import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `payload migrate:create` — every migration's up()/
    // down() signature includes payload/req params from Payload's own
    // fixed template, unused unless a migration actually needs them.
    // Not hand-written, not worth hand-editing per migration.
    "migrations/**",
  ]),
]);

export default eslintConfig;
